---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.7.5"
  - PUPPET_VERSION="~> 3.7.5" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.5" STRINGIFY_FACTS=no
  - PUPPET_VERSION="~> 3.7.5" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.5" ORDERING=random
matrix:
  exclude:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.3.0"
  allow_failures:
    - env: PUPPET_VERSION="~> 3.7.5" STRICT_VARIABLES=yes
    - rvm: 2.2.2
