HOSTS:
  ubuntu-server-12042-x64-master:
    roles:
      - master
      - standalone_master
    platform: ubuntu-server-12.04-amd64
    box: ubuntu-server-12042-x64-vbox4210-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-server-12042-x64-agent:
    roles:
      - agent
      - standalone_master_agent
    platform: ubuntu-server-12.04-amd64
    box: ubuntu-server-12042-x64-vbox4210-nocm
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
